# Generated by Django 4.0.6 on 2023-04-04 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('288b499d-e011-4248-ac0a-4e4f91a9bf74'), editable=False, primary_key=True, serialize=False)),
                ('todo_title', models.CharField(max_length=200)),
                ('todo_description', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
