# Generated by Django 4.0.6 on 2023-04-04 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('48d0beeb-74ec-4223-b3ed-7c1db5f6553a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
