# Generated by Django 4.0.6 on 2023-04-04 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4b47fcda-8f65-428b-9a9e-c9a6249e1992'), editable=False, primary_key=True, serialize=False),
        ),
    ]
