# Generated by Django 4.0.6 on 2023-04-04 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_todo_options_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1f339340-6185-45e9-ae01-2e8e195e900f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
