# Generated by Django 4.0.6 on 2023-04-04 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_timingtodo_id_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timingtodo',
            old_name='timinig',
            new_name='timing',
        ),
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9a2bccb6-00b0-42da-b250-daff877d75e3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('98fb222d-9007-4c55-afe9-99b270bae05c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
