# Generated by Django 4.0.6 on 2023-04-04 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_todo_user_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a453cb52-ef11-49fa-98e4-a9fc4791cbbd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0045568c-479b-45f7-9147-0c813259f468'), editable=False, primary_key=True, serialize=False),
        ),
    ]
